# SPDX-License-Identifier: Apache-2.0
## This can be used to override the image registry at a global level, which
## can be useful when pulling from private hosts.
##
# global:
#  imageRegistry: myRegistryName

## Properties related to core Marquez backend functionality and API usage
##
marquez:
  ## Kubernetes service account used for deployment
  ##
  serviceAccount: "default"
  ## Number of desired replicas
  ##
  replicaCount: 1
  ## Marquez image version
  ## ref: https://hub.docker.com/r/marquezproject/marquez/tags/
  ##
  image:
    registry: docker.io
    repository: marquezproject/marquez
    tag: 0.50.0
    pullPolicy: IfNotPresent
  ## Postgres database settings where Marquez data will persist
  ##
  db:
    host: marquez-postgresql
    port: 5432
    name: marquez
    user: marquez
    password: marquez
  ## Indicates if Flyway database migration will execute upon deployment
  ##
  migrateOnStartup: true
  ## Marquez will run using this hostname
  ##
  hostname: localhost
  ## Marquez API will run on this port
  ##
  port: 5000
  ## Heath and liveness checks will run on this port
  ##
  adminPort: 5001
  ## Resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # Typically best to not specify these settings, unless you've got a specific
    # reason to customize.
    limits: {}
    #    cpu: 200m
    #    memory: 1Gi
    requests: {}
    #    memory: 256Mi
    #    cpu: 250m
  podAnnotations: {}
  ## - name:
  ##   value:
  ##
  ## Allowing passing in of extra container definitions to be run inside the marquez deployment - for example to allow cloud-sql-proxy container
  extraContainers: []

## Properties related to Marquez frontend functionality
##
web:
  ## Enables creation of the web UI
  ##
  enabled: true
  ## Number of desired replicas
  ##
  replicaCount: 1
  ## Marquez web image version
  ## ref: https://hub.docker.com/r/marquezproject/marquez-web/tags/
  ##
  image:
    registry: docker.io
    repository: marquezproject/marquez-web
    tag: 0.50.0
    pullPolicy: IfNotPresent
  ## Marquez website will run on this port
  ##
  port: 3000
  ## Resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # Typically best to not specify these settings, unless you've got a specific
    # reason to customize.
    limits: {}
    #    cpu: 200m
    #    memory: 1Gi
    requests: {}
    #    memory: 256Mi
    #    cpu: 250m


global:
  security:
    allowInsecureImages: true

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
##
postgresql:
  ## @param postgresql.enabled Deploy PostgreSQL container(s)
  ##
  enabled: true
  ## Bitnami PostgreSQL image version
  ## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
  ## @param image.registry PostgreSQL image registry
  ## @param image.repository PostgreSQL image repository
  ## @param image.tag PostgreSQL image tag (immutable tags are recommended)
  ##
  image:
    repository: bitnamilegacy/postgresql
    tag: 12.1.0
  ## Authentication parameters
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-user-on-first-run
  ##

  auth:
    ## @param auth.username Name for a custom user to create
    ##
    username: marquez
    ## @param auth.database Name for a custom database to create
    ##
    database: marquez

    postgresPassword: postgres

    password: marquez

    replicationPassword: replication

## Additional labels to all the deployed resources; note that
## the following standard labels will automatically be applied.
##   app.kubernetes.io/name, helm.sh/chart,
##   app.kubernetes.io/instance, app.kubernetes.io/managed-by
##
commonLabels: {}
## - name: app.kubernetes.io/part-of
##   value: "my-awesome-system"

## Add annotations to all the deployed resources
##
commonAnnotations: {}
## - name: support-contact
##   value: "ops-team-name"
##

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
service:
  type: ClusterIP
  port: 80
  ## Service annotations done as key:value pairs
  ##
  annotations:

## Configure the ingress resource that allows you to access the
## Marquez installation, without relying on local port forwarding.
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## Set to true to enable ingress record generation
  ##
  enabled: true
  hosts:
  - marquez.localtest.me
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Open Lineage UI
    gethomepage.dev/group: Data Governance
    gethomepage.dev/icon: https://avatars.githubusercontent.com/u/40306238?v=4
    gethomepage.dev/name: Marquez